"""Shared real-Panda construction for the M2b solver-quality probes."""

from __future__ import annotations

import torch

from better_robot.data_model.model import Model
from better_robot.kinematics import forward_kinematics
from better_robot.optim import (
    Bounds,
    Problem,
    RobotVariable,
)
from better_robot.residuals.limits import JointPositionLimit
from better_robot.residuals.pose import PoseResidual
from better_robot.residuals.regularization import RestResidual


def panda_frame_id(model: Model) -> int:
    """Return the canonical Panda hand frame used by the audit probes."""
    for name in ("body_panda_hand", "body_panda_link8", "body_panda_link7"):
        if name in model.frame_name_to_id:
            return model.frame_id(name)
    raise AssertionError("Panda end-effector frame is missing")


def bounded_start(model: Model) -> torch.Tensor:
    """Return the shared audit start, including Panda joint-4 clamping."""
    return model.q_neutral.clamp(model.lower_pos_limit, model.upper_pos_limit).clone()


def sample_nearby_configurations(
    model: Model,
    batch: int,
    *,
    seed: int,
    fraction: float,
) -> torch.Tensor:
    """Sample a seeded local in-bounds box around the shared start."""
    generator = torch.Generator(device=model.q_neutral.device).manual_seed(seed)
    lower = model.lower_pos_limit
    upper = model.upper_pos_limit
    span = upper - lower
    start = bounded_start(model).expand(batch, -1)
    perturbation = (
        fraction
        * span
        * (
            torch.rand(
                (batch, model.nq),
                dtype=start.dtype,
                device=start.device,
                generator=generator,
            )
            - 0.5
        )
    )
    # Keep targets strictly interior.  This probe exercises solver parity,
    # while P1 separately drives the bounded active-set regression.
    margin = 1e-3 * span
    return (start + perturbation).clamp(lower + margin, upper - margin)


def target_poses(model: Model, configurations: torch.Tensor) -> torch.Tensor:
    """Evaluate the hand targets generated by known feasible configurations."""
    data = forward_kinematics(model, configurations, compute_frames=True)
    return data.frame_pose_world[..., panda_frame_id(model), :].clone()


def make_panda_problem(
    model: Model,
    target: torch.Tensor,
    *,
    regularized: bool,
) -> Problem:
    """Build the M2a block problem used by P1/P3/P4/P6 and P7."""
    q = RobotVariable(
        model,
        bounded_start(model),
        name="q",
        bounds=Bounds(lower=model.lower_pos_limit, upper=model.upper_pos_limit),
    )
    pose = PoseResidual(
        q,
        frame_id=panda_frame_id(model),
        target=target,
        name="pose",
    )
    pose.group_size = 6
    residuals = [pose]
    if regularized:
        residuals.extend(
            (
                JointPositionLimit(q, name="limits", weight=0.1),
                RestResidual(q, model.q_neutral, name="rest", weight=0.01),
            )
        )
    return Problem(residuals)
