"""FK regression oracle.

Compares current forward-kinematics output against
``tests/kinematics/fk_reference.npz``. The file is committed and
re-generated only by an explicit run of ``_generate_fk_reference.py``
after a deliberate algorithmic change.

Oracle version 3 was generated by the batched matrix FK lane. The comparison
still sign-aligns quaternions (:func:`_sign_align_poses`) so a future gauge
change surfaces as the deliberate-regeneration decision it is rather than a
wall of sign flips. Pinocchio parity (``tests/test_pinocchio``) remains the
fp64 rotation-matrix ground truth.

Skips automatically if ``fk_reference.npz`` is missing — the oracle file
ships only after the first commit of the bench infrastructure.

See ``docs/conventions/testing.md §4.5``.
"""

from __future__ import annotations

import dataclasses
from pathlib import Path

import numpy as np
import pytest
import torch

import better_robot as br

REF_PATH = Path(__file__).parent / "fk_reference.npz"


def _sign_align_poses(actual: np.ndarray, reference: np.ndarray) -> np.ndarray:
    """Flip each pose quaternion to the sign of its dot with the reference.

    The matrix FK lane emits canonical-sign quaternions, so a pose may carry
    ``-q`` (the same rotation) relative to the stored oracle. Aligning by the
    dot sign keeps the regression gauge-robust at the original tolerance instead
    of loosening it. ``actual``/``reference`` are ``(..., 7)`` poses.
    """
    aligned = np.array(actual, copy=True)
    actual_q = aligned[..., 3:7]
    reference_q = reference[..., 3:7]
    dots = np.sum(actual_q * reference_q, axis=-1, keepdims=True)
    aligned[..., 3:7] = actual_q * np.where(dots < 0.0, -1.0, 1.0)
    return aligned


def _load_panda():
    pytest.importorskip("robot_descriptions")
    from robot_descriptions import panda_description
    from better_robot.io import build_model, parse_urdf

    # The frozen oracle predates reduced mimic coordinates and contains two
    # independent finger entries. Keep it as an explicit full-space algorithm
    # regression; constrained behavior has dedicated reduced-map tests.
    ir = parse_urdf(panda_description.URDF_PATH)
    ir.joints = [
        dataclasses.replace(
            joint,
            mimic_source=None,
            mimic_multiplier=1.0,
            mimic_offset=0.0,
        )
        for joint in ir.joints
    ]
    return build_model(ir, dtype=torch.float64)


def _load_g1():
    pytest.importorskip("robot_descriptions")
    from robot_descriptions import g1_description

    return br.load(g1_description.URDF_PATH, free_flyer=True, dtype=torch.float64)


@pytest.fixture(scope="module")
def reference():
    if not REF_PATH.exists():
        pytest.skip(f"oracle file {REF_PATH.name} not present; run _generate_fk_reference.py")
    return np.load(REF_PATH)


@pytest.mark.parametrize("name,loader", [("panda", _load_panda), ("g1", _load_g1)])
def test_fk_matches_oracle(name, loader, reference) -> None:
    model = loader()
    qs = torch.from_numpy(reference[f"{name}_q"])
    expected_joints = reference[f"{name}_joint_pose_world"]
    expected_frames = reference[f"{name}_frame_pose_world"]
    for i in range(qs.shape[0]):
        data = br.forward_kinematics(model, qs[i], compute_frames=True)
        np.testing.assert_allclose(
            _sign_align_poses(data.joint_pose_world.detach().cpu().numpy(), expected_joints[i]),
            expected_joints[i],
            atol=1e-10,
            rtol=1e-10,
            err_msg=f"{name}: joint pose mismatch at sample {i}",
        )
        np.testing.assert_allclose(
            _sign_align_poses(data.frame_pose_world.detach().cpu().numpy(), expected_frames[i]),
            expected_frames[i],
            atol=1e-10,
            rtol=1e-10,
            err_msg=f"{name}: frame pose mismatch at sample {i}",
        )
